name: Publish to GitHub Packages

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Pack
      run: dotnet pack --configuration Release

    - name: Publish to GitHub Packages
      run: dotnet nuget push ./bin/Release/*.nupkg --source https://nuget.pkg.github.com/USERNAME/index.json --api-key ${{ secrets.GITHUB_TOKEN }}
